name: onlineshop
description: "A new Flutter project."
publish_to: 'none'
version: 0.1.0

environment:
  sdk: '>=3.2.3 <4.0.0'

dependencies:
    firebase_auth: 
    firebase_core: 
    firebase_ui_auth: 
    firebase_ui_oauth_google: 
    flutter:
        sdk: flutter
    google_sign_in:
    shared_preferences: 
    flutter_screenutil:
    firebase_analytics: ^10.8.7 
    banner_carousel:
    firebase_storage:
    get:
    cloud_firestore:
    uuid: 
    provider:
    
    

dev_dependencies:
    flutter_test:
        sdk: flutter
    flutter_lints: 
    flutter_launcher_icons:

flutter_icons:
  ios: true
  android: true
  image_path_ios: "assets/launcher/icon.png"
  image_path_android: "assets/launcher/icon.png" 
  flutter_test:
  

flutter:
  uses-material-design: true
  assets:
    - assets/
    - assets/items/