name: onlineshop
description: "A new Flutter project."
publish_to: 'none'
version: 0.1.0

environment:
  sdk: '>=3.2.3 <4.0.0'

dependencies:
    firebase_auth: 
    firebase_core: 
    firebase_ui_auth: 
    firebase_ui_oauth_google: 
    flutter:
        sdk: flutter
    google_sign_in:
    shared_preferences: 
    flutter_screenutil:

dev_dependencies:
    flutter_test:
        sdk: flutter
    flutter_lints: 


flutter:
  uses-material-design: true
  assets:
    - assets/
 